# can test like postman with REST client extension

#index
GET http://localhost:8000/api/product Http/1.1

###
#create
POST http://localhost:8000/api/product/create Http/1.1
Content-Type: application/json

{
    "productTitle": "Chap-stick",
    "productPrice": 1.95,
    "productDescription": "for your lips."
}

###
#show
GET http://localhost:8000/api/product/5e4c057ac9c2683e5cc4d6a4 Http/1.1

###
#update
PUT  http://localhost:8000/api/product/update/5e4c057ac9c2683e5cc4d6a4 Http/1.1
Content-Type: application/json

{
    "productTitle": "Goose Jacket",
    "productPrice": 1100,
    "productDescription": "Stay warm."
}

###
#destoy
DELETE http://localhost:8000/api/product/destroy/5e4c185b5dccf44d64643e21 Http/1.1